### ISSUE TITLE
Distinguish between lees and greater in two.sided alternative

### ISSUE THREAD

**Issue by MislavSag** [ottosven/backCUSUM#2]
Hi,

If I use `two.sided` alternative, how can I know if the rejection is for the 'less' or or 'greater'? 

That is how can I say from the output if structural breaks mean lower or higher mean?

**Comment by ottosven** [comment]
Hi Mislav, this option is not implemented within the `two.sided` test (within this option the detector is always defined with respect to its absolute value). Also note that a two sided test is in general not designed to answer this question. 

You can try both the `less` and the `greater` option. If one of the two rejects you know the direction of rejection. But note that you have to adjust for the significance level, which is then twice as large.

**Comment by MislavSag** [comment]
When you say significance level is twice as large, you mean I have to compare `statistic` with `critical.value` * 2?

But output of 'greater' for critical values is the same as in 'two.sided'.

**Comment by ottosven** [comment]
Sorry for the late answer. The critical value output for 'greater' is not the same as for 'two.sided'. If you follow the example I have added to the documentation of the function (see `?SBQ.mon`) you see that `SBQ.mon(y~1+x+I(x^2), T, alternative = "two.sided")$critical.value` is different than `SBQ.mon(y~1+x+I(x^2), T, alternative = "greater")$critical.value`. The critical value for level 10% for 'two.sided' is the critical value for level 5% for 'greater'. You can also use the function `get.crit.SBQ.mon` to find the correct critical value for you case. Please do not multiply the critical value by 2, this is not correct.

**Comment by MislavSag** [comment]
Thanks for the clarification. In the end, I try to tune the parameter in a way to get the most robust cumulative returns in my strategy. I think the only problem is that, for longer horizons, I change the position too late because the break can be somewhere on the beginning of the window. I don't use `SBQ.mon`.  I am not sure it is suitable for rolling structural break aproximation.
